### ISSUE TITLE
预览预计什么时候出来呢？

### ISSUE THREAD

**Issue by eggbucket** [yangyuji/h5-factory#1]
预览预计什么时候出来呢？或者将采用何种技术生产html页面

**Comment by yangyuji** [comment]
暂时还没决定好方案，初步定了两个方案：1、做到一个node后端项目里；2、直接在这里写一个全样式和脚本的模板页面，用js动态渲染

**Comment by yangyuji** [comment]
> 预览预计什么时候出来呢？或者将采用何种技术生产html页面

暂时还没决定好方案，初步定了两个方案：1、做到一个node后端项目里；2、直接在这里写一个全样式和脚本的模板页面，用js动态渲染。

**Comment by eggbucket** [comment]
预览出来基本就成型了，项目不错，持续关注。谢谢

**Comment by yangyuji** [comment]
已经发布部分组件的预览功能，问题还较多，接下来慢慢完善
