### ISSUE TITLE
你好，预览提示页面初始化失败。请问是什么问题呢

### ISSUE THREAD

**Issue by zhanglei518** [yangyuji/h5-factory#4]
你给的案例和自己down的demo里面都是预览无效。。。

**Comment by yangyuji** [comment]
原因：我把页面配置的两个参数去掉了，忘记修改预览代码了，稍后修复。
PS：预览不是我要做的重点，我要做的是如何搭建这样一个系统，至于把数据消费成什么样，有使用者自己去做，比如我在考虑把数据消费成小程序等。

**Comment by ideacco** [comment]
我也出现了这个问题。

**Comment by ideacco** [comment]
另外我可以把生成的页面输出成一张图么？

**Comment by yangyuji** [comment]
> 另外我可以把生成的页面输出成一张图么？

你说的是html2canvas.js的功能吧？

**Comment by ideacco** [comment]
谢谢，我去看一下

**Comment by yangyuji** [comment]
已处理预览提示初始化失败的bug，感谢关注！
