### ISSUE TITLE
在页面含有多个表单控件的时候  无论点击的是哪个表单  增加表单项只有第一个表单控件生效，其余表单都不受控制

### ISSUE THREAD

**Issue by sodagreen574** [yangyuji/h5-factory#9]
在页面含有多个表单控件的时候  无论点击的是哪个表单  增加表单项只有第一个表单控件生效，其余表单都不受控制

**Comment by yangyuji** [comment]
> 在页面含有多个表单控件的时候 无论点击的是哪个表单 增加表单项只有第一个表单控件生效，其余表单都不受控制

已经处理，感谢！
